# Generated by https://quicktype.io
import strawberry
from typing import List, Optional
from datetime import datetime

 

@strawberry.type
class More:
    id: str
    name: str
    lastname: str
    email: str
    birth: datetime
    gender_id: str
    status: bool
    is_user: bool
    user_id: str
    is_children: bool
    age: int
    days_birth: int

    def __init__(self, id: str, name: str, lastname: str, email: str, birth: datetime, gender_id: str, status: bool, is_user: bool, user_id: str, is_children: bool, age: int, days_birth: int) -> None:
        self.id = id
        self.name = name
        self.lastname = lastname
        self.email = email
        self.birth = birth
        self.gender_id = gender_id
        self.status = status
        self.is_user = is_user
        self.user_id = user_id
        self.is_children = is_children
        self.age = age
        self.days_birth = days_birth

@strawberry.type
class Usuario:
    id: str
    phone: str
    lastCode: str
    status: str
    isActive: bool
    token: str
    ci: str
    city: str
    password: str
    state: datetime

    def __init__(self, id: str, phone: str, lastCode: int, status: str, isActive: bool, token: str, ci: int, city: str, password: str, state: datetime) -> None:
        self.id = id
        self.phone = phone
        self.lastCode = lastCode
        self.status = status
        self.isActive = isActive
        self.token = token
        self.ci = ci
        self.city = city
        self.password = password
        self.state = state



@strawberry.type
class LoginResponse:
    statusCode: int
    token: str
    usuario: Usuario
    more: More
    resp: bool
    message: str

    def __init__(self, statusCode: int, token: str, usuario: Usuario, more: More, resp: bool, message: str) -> None:
        self.statusCode = statusCode
        self.token = token
        self.usuario = usuario
        self.more = more
        self.resp = resp
        self.message = message
